### ISSUE TITLE
Installation with 4.03 as system compiler: ERROR: Preinstalled ocamlbuild detected at /usr/lib64/ocaml/ocamlbuild

### ISSUE THREAD

**Issue by edwintorok** [ocaml/ocamlbuild#109]
On Gentoo ~amd64 with OCaml 4.03 as system compiler I get :
```
#=== ERROR while installing ocamlbuild.0.9.2 ==================================#
# opam-version 1.2.2
# os           linux
# command      make check-if-preinstalled all opam-install
# path         /home/edwin/.opam/obt/build/ocamlbuild.0.9.2
# compiler     system (4.03.0)
# exit-code    2
# env-file     /home/edwin/.opam/obt/build/ocamlbuild.0.9.2/ocamlbuild-22037-c61e7b.env
# stdout-file  /home/edwin/.opam/obt/build/ocamlbuild.0.9.2/ocamlbuild-22037-c61e7b.out
# stderr-file  /home/edwin/.opam/obt/build/ocamlbuild.0.9.2/ocamlbuild-22037-c61e7b.err
### stdout ###
# if test -d /usr/lib64/ocaml/ocamlbuild; then\
#   >&2 echo "ERROR: Preinstalled ocamlbuild detected at"\
#        "/usr/lib64/ocaml/ocamlbuild";\
#   >&2 echo "Installation aborted; if you want to bypass this"\
#         "safety check, pass CHECK_IF_PREINSTALLED=false to make";\
#   exit 2;\
# fi
### stderr ###
# ERROR: Preinstalled ocamlbuild detected at /usr/lib64/ocaml/ocamlbuild
# Installation aborted; if you want to bypass this safety check, pass CHECK_IF_PREINSTALLED=false to make
# make: *** [Makefile:333: check-if-preinstalled] Error 2
```

ocamlbuild is installed system-wide too (`dev-ml/ocamlbuild` is pulled in by `dev-ml/cmdliner`, pulled in by `dev-ml/opam`).

I work this around with `opam install --fake ocamlbuild` (or I could export that env var as suggested), but it doesn't feel like the right solution.
Would it be possible to take advantage of the opam `available: preinstalled` flag? (indicating that we are in a system switch), although unlike `camlp4` the `ocamlbuild` package is not closely tied to the compiler and one might want to install a newer version anyway?

**Comment by gasche** [comment]
I think this is another occurrence of the bugs fixed by #7313, which should be fixed at the next release.

**Comment by gasche** [comment]
0.9.3 was just released. Could you test whether you can reproduce the bug there?

**Comment by edwintorok** [comment]
Still a problem with ocamlbuild 0.9.3.
This works: `CHECK_IF_PREINSTALLED=false opam install ocamlbuild`
This fails the same as before: `opam install ocamlbuild`

Why is the preinstalled check there? (was it due to that bug you mentioned?)

**Comment by gasche** [comment]
So, thinking about it, I was mistaken in suspecting it was this issue. In the aforementioned issue, the "preinstalled check" mistakenly assumes that it is in a system installation and conflicts with system-installed ocamlbuild. In your case, you are actually running from the system switch, which I did not take into consideration in my reply.

The preinstalled check is designed to prevent an opam ocamlbuild install from happening in a switch that already has ocamlbuild provided by the compiler (in OCaml versions where ocamlbuild is distributed and installed by the compiler). I believe that it is reasonable for this check to fail in your case, as you have two different ocamlbuild install that are fighting for being the `ocamlbuild` executable in your PATH, so there is indeed a conflict.

`opam install --fake ocamlbuild` looks like a reasonable solution to your problem.

Another solution could be for opam-repository to provide an ocamlbuild.system version that checks that there is a system-installed ocamlbuild and does nothing else. But then I don't know how to define this package such that only the people in your situation would install it! (If the opam solver tries to install it in non-system switches, or in system switches that don't have a system ocamlbuild package, it is problematic.)

So I think that this is more of an opam-repository or opam expressivity issue than an ocamlbuild bug (the failure here is intended, as far as I understand). What do you think?

**Comment by edwintorok** [comment]
The opam file says `available: [ocaml-version >= "4.03"]`, shouldn't that prevent the problem you are describing? (that there is ocamlbuild provided by the OCaml compiler for older OCaml versions). 
For ocaml `4.02.3` I get `ocamlbuild` version `0` installed (which is an empty package).

One possibility would be to drop the preinstalled check, but I don't know if anything would break if there are 2 ocamlbuilds (one system, and another in .opam, possibly newer).
What if you perform the equivalent of install `--fake` when you detect the preinstalled version? (i.e. you don't build/install anything).

I think its important to have a nice out-of-box experience here which doesn't depend on the ocaml version: when distributions start switching to 4.03 as their system compiler more people might run into this problem, and installing nearly any package would fail with this error in ocamlbuild.
I don't know if the right place to fix this is ocamlbuild's opam file, or maybe opam/ocamlfind itself.
Should some people on the opam side be CC-ed on this issue?

**Comment by gasche** [comment]
So it looks like camlp4 handles this issue with just a `4.0x+system` version that requires `preinstalled` (I guess that's a check that we are on the system switch), while non-`+system` versions require `!preinstalled`, so they can only be installed on non-system switches.

If I understand correctly, this means that on the system switch you are forced to install the system camlp4 package. Would such an approach for ocamlbuild seem acceptable for you?

@diml could you maybe confirm that this is the semantics of Camlp4's `+system`? Would you recommend this choice for ocamlbuild? Currently (see discussion above), `opam install ocamlbuild` from a system switch will succeed (and work as expected) if no system ocamlbuild is installed, but it fails (on my check that there is no compiler-provided ocamlbuild around) if system-ocamlbuild is installed, and @edwintorok had to work around this through `opam install --fake ocamlbuild`.

**Comment by whitequark** [comment]
Triage: waiting on @diml's answer.

**Comment by diml** [comment]
Sorry, I missed this mail. This is indeed the semantic of Camlp4's `+system`. The only reason it is still like this is because many old packages still do `-I +camlp4`, so camlp4 must be installed in `ocamlc -where`. I would like to stop supporting this and just install camlp4 as a regular package, and even depend on `ocaml-migrate-parsetree` for simplicity. However last time we tried that it broke tons of stuff (/cc @avsm )

**Comment by madroach** [comment]
I just hit this when upgrading the system compiler on OpenBSD to 4.07.1.
The OpenBSD port of ocamlbuild happened to be installed while initialising the system compiler switch in OPAM.
Using ``--fake`` is no viable option, because of what would happen when the system ocamlbuild would be uninstalled, for example on the next run of [``pkg_delete -a``](https://man.openbsd.org/pkg_delete).

What is this ``CHECK_IF_PREINSTALLED`` actually trying to protect against?

As far as ``PATH`` is concerned, the user can decide which instance of ocamlbuild to use  by arranging his ``PATH`` accordingly.
Ports building, which wants to use the system ocamlbuild in ``/usr/local`` is isolated from the users ``PATH``. So no problem there either.
